WIP: add test studio
Aratramba/sanity-plugin-media-library pull request #22
Opened 2021-02-04 15:10 UTC by Aratramba

2021-02-09 12:22 UTC, dennispassway requested changes
Overall really nice. I think th estudio should not be mixed with the plugin tho and it should be in a seperate test fodler

2021-02-09 12:22 UTC, dennispassway commented on package.json
> +    "@sanity/vision": "^2.2.6",
Do we use vision?

2021-02-09 12:22 UTC, dennispassway commented on package.json
> +    "prop-types": "^15.7",
do we use prop-types?

2021-02-09 12:22 UTC, dennispassway commented on package.json
> +    "react": "^17.0",
react can be removed, since it is already listes as peer dependency

2021-02-09 12:22 UTC, dennispassway commented on package.json
> +    "@sanity/base": "^2.3.2",
already listed as peer dependecny

2021-02-09 12:22 UTC, dennispassway commented on src/components/DeleteModal.tsx
> +          Are you sure you want to delete {plural ? `these ${assets.length} assets` : 'this asset'}?
'these' could now be removed. nice improvement 🌱

2021-02-09 12:22 UTC, dennispassway commented on src/components/MediaLibrary.tsx
> +            <StyledMessage>No files yet</StyledMessage>
```suggestion
            <StyledMessage>No assets yet</StyledMessage>
```

2021-02-09 12:22 UTC, dennispassway commented on studio/package.json
> +{
Does this belogn here?

2021-02-09 12:22 UTC, dennispassway commented on studio/plugins/.gitkeep
> +User-specific packages can be placed here
This file can be deleted.

2021-02-09 12:22 UTC, dennispassway commented on studio/sanity.json
> +    "projectId": "q74m7lt8",
```suggestion
    "projectId": null,
```

2021-02-09 12:22 UTC, dennispassway commented on studio/sanity.json
> +    "dataset": "production"
```suggestion
    "dataset": null
```

2021-02-09 12:22 UTC, dennispassway commented on studio/sanity.json
> +  "env": {
vision can be removed

2021-02-09 12:22 UTC, dennispassway commented on test/asset-source.test.js
> +// Needs to be higher than the default Playwright timeout
add why

2021-02-09 12:22 UTC, dennispassway commented on test/asset-source.test.js
> +jest.setTimeout(40 * 1000);
```suggestion
jest.setTimeout(40000);
```

2021-02-09 12:22 UTC, dennispassway commented on test/asset-source.test.js
> +    await page.waitForTimeout(2000);
This fails on slow internet speeds right?

2021-02-09 12:22 UTC, dennispassway commented on test/asset-source.test.js
> +  // it('should remove unused tag', async () => {
This should be removed or fixed before merging

2021-02-09 12:22 UTC, dennispassway commented on test/asset-source.test.js
> +    await page.waitForTimeout(2000);
Same for all waitForTimeout, maybe put the time in a variable up top with a comment that this is the max time the requests may take, so slower internet conneciton can simply up the variable

2021-02-09 14:06 UTC, Aratramba commented on package.json
> +    "@sanity/vision": "^2.2.6",
pretty handy for development

2021-02-09 14:07 UTC, Aratramba commented on studio/package.json
> +{
there needs to be a package.json inside a studio folder

2021-02-09 14:13 UTC, Aratramba commented on studio/sanity.json
> +    "projectId": "q74m7lt8",
I think we can leave these here so you can quickstart development. If you need to change it, you can use sanity reserved variables to override them https://www.sanity.io/docs/studio-environment-variables#reserved-variable-names-cc239c4841f0

2021-02-09 14:13 UTC, Aratramba commented on README.md
> +Create a Sanity bot token with write access at manage.sanity.io. Add a dataset named 'testing'. Then make a .env file  inside the root folder:
these can be overridden by env vars https://www.sanity.io/docs/studio-environment-variables#reserved-variable-names-cc239c4841f0

2021-02-15 10:34 UTC, dennispassway requested changes

2021-02-15 10:34 UTC, dennispassway commented on .gitignore
> +.env
```suggestion
.env*
```

to prevent all sort of env files from being commited

2021-02-15 10:34 UTC, dennispassway commented on README.md
> +To test the studio while developing, make a symlink inside the `/test/studio/plugins` folder that links to the root directory. Then run `sanity start` in `test/studio`.
```suggestion
Optional: To use the included studio while developing, make a symlink inside the `/test/studio/plugins` folder that links to the root directory. Then run `sanity start` in `test/studio`. You can also add the plugin to the plugins directory in a Sanity studio of your own.
```

2021-02-15 10:34 UTC, dennispassway commented on README.md
> +Create a Sanity bot token with write access at [manage.sanity.io](manage.sanity.io). Add a dataset named 'testing'. Then make a .env file  inside the `/test` folder:
The dataset testing should also be in the env file?

2021-02-15 10:34 UTC, dennispassway commented on test/studio/package.json
> +  "author": "Arjen <aratramba@gmail.com>",
Sure you want your email to appear here?

2021-02-15 10:34 UTC, dennispassway commented on test/studio/sanity.json
> +    "projectId": "q74m7lt8",
these should be null by default i think

2021-02-15 10:34 UTC, dennispassway commented on test/studio/sanity.json
> +        "@sanity/vision"
cant we remove vision?

2021-06-18 14:08 UTC, merged